
export const charactersActions = {
    GET_CHARACTERS_PENDING: "GET_CHARACTERS_PENDING",
    GET_CHARACTERS_ERROR: "GET_CHARACTERS_ERROR",
    GET_CHARACTERS_SUCCESS: "GET_CHARACTERS_SUCCESS"
};

export const characterActions = {
    GET_CHARACTER_PENDING: "GET_CHARACTER_PENDING",
    GET_CHARACTER_ERROR: "GET_CHARACTER_ERROR",
    GET_CHARACTER_SUCCESS: "GET_CHARACTER_SUCCESS"
};
