
export const searchCharactersActions = {
    SEARCH_CHARACTERS_PENDING: "SEARCH_CHARACTERS_PENDING",
    SEARCH_CHARACTERS_ERROR: "SEARCH_CHARACTERS_ERROR",
    SEARCH_CHARACTERS_SUCCESS: "SEARCH_CHARACTERS_SUCCESS"
};

export const charactersActions = {
    GET_CHARACTERS_PENDING: "GET_CHARACTERS_PENDING",
    GET_CHARACTERS_ERROR: "GET_CHARACTERS_ERROR",
    GET_CHARACTERS_SUCCESS: "GET_CHARACTERS_SUCCESS",
};

export const characterActions = {
    GET_CHARACTER_PENDING: "GET_CHARACTER_PENDING",
    GET_CHARACTER_ERROR: "GET_CHARACTER_ERROR",
    GET_CHARACTER_SUCCESS: "GET_CHARACTER_SUCCESS"
};
